PNG_NAMES = "/Users/BigBlue/Documents/Programming/Python/misc/data/saved_image_names.txt"
IMAGES_DIRECTORY = "/Users/BigBlue/Downloads/cartoonset10k"
DEFAULT_CHOICES = "/Users/BigBlue/Documents/Programming/Python/misc/data/default_choices.json"
FACE_PROPERTIES = ["eye_angle", "eye_lashes", "eye_lid", "chin_length", "eyebrow_weight", "eyebrow_shape", "eyebrow_thickness", "face_shape", "facial_hair", "hair", "eye_color", "face_color","hair_color", "glasses", "glasses_color", "eye_slant", "eyebrow_width", "eye_eyebrow_distance"]
DATA_DIRECTORY = "/Users/BigBlue/Documents/Programming/Python/misc/data/"
PERSONAL_CHOICES = "/Users/BigBlue/Documents/Programming/Python/misc/data/save_choices.json"
DEBUGGING_SAVE = "/Users/BigBlue/Documents/Programming/Python/misc/data/debug.txt"
SAVE_IMAGE_NAMES = "/Users/BigBlue/Documents/Programming/Python/misc/data/saved_image_names.txt"
MAX_PORTRAITS = 50
